const EMAIL_TO='valentineuromed@gmail.com';
// URL de l'application Web Google Apps Script.
// Après déploiement de Code.gs, colle ici l'URL qui se termine par /exec.
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbwXoa9jjmye4AMvUFHiK_2wChRKWF-yA0qqWSLTHQJYY9Vr1h3NddRwkLQe8nwUvkH5/exec';
// Optionnel : si tu définis APP_TOKEN dans les propriétés du script,
// mets la même valeur ici. Sinon laisse une chaîne vide.
const APP_TOKEN='';

const sections=[
['Potence',['Potence (fixation, sangle, enrouleur …)']],
['Barrières',['Espacement entre la tête du lit et la barrière (< 60 mm)*','Espacement entre 1/2 barrières (< 60 ou > 318 mm)*','État, sens de montage, adaptation au lit …','Fixation des barrières et verrouillage en position haute (fermée)']],
['CONTRÔLE VISUEL',['Identification - étiquetage','Propreté générale / aspect extérieur (vérin, capot de protection, …)','État de fixation des panneaux tête et pieds','Plan de couchage (sommier)','Serrages des boulonneries, axes et fixation des goupilles','Corrosion, soudures / humidité']],
['CONTRÔLE FONCTIONNEL',['Parties mobiles (hauteur variable, relève buste, relève jambes, proclive, déclive …)','Télécommande (boutons, voyants, système de verrouillage)','Roues (pivotement, roulage …)','Freins (blocage)','Absence de nuisances sonores (grincements)']],
['CONTRÔLE ÉLECTRIQUE',['État des câbles électriques des prises et des connecteurs',"État des équipements électriques (bloc d'alimentation, vérins …)",'Essai récurrent suivant norme NF EN 62353 (voir le rapport d’essai pour détails conformité)']]
];
const root=document.getElementById('controls');
sections.forEach(([title,items],si)=>{let t=document.createElement('table');t.className='control';t.innerHTML=`<thead><tr><th class="item">${title}</th><th>Non applicable</th><th>Conforme</th><th>Non conforme</th></tr></thead><tbody></tbody>`;let tb=t.querySelector('tbody');items.forEach((it,i)=>{let name=`c_${si}_${i}`;let special=(title==='CONTRÔLE ÉLECTRIQUE'&&i===2);let tr=document.createElement('tr');tr.innerHTML=`<td class="item">${it}</td><td>${special?'':`<input type="radio" name="${name}" value="Non applicable">`}</td><td>${special?'':`<input type="radio" name="${name}" value="Conforme">`}</td><td>${special?'':`<input type="radio" name="${name}" value="Non conforme">`}</td>`;tb.appendChild(tr)});root.appendChild(t)});

document.getElementById('date').valueAsDate=new Date();
function setupCanvas(id){const c=document.getElementById(id),ctx=c.getContext('2d');function resize(){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.scale(d,d);ctx.lineWidth=2;ctx.lineCap='round'}resize();let drawing=false,last=null;c.addEventListener('pointerdown',e=>{drawing=true;last=[e.offsetX,e.offsetY];c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drawing)return;ctx.beginPath();ctx.moveTo(last[0],last[1]);ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke();last=[e.offsetX,e.offsetY]});c.addEventListener('pointerup',()=>drawing=false);c.addEventListener('pointercancel',()=>drawing=false);return c}const sigTech=setupCanvas('sigTech'),sigClient=setupCanvas('sigClient');document.querySelectorAll('.clear').forEach(b=>b.onclick=()=>{const c=document.getElementById(b.dataset.canvas);c.getContext('2d').clearRect(0,0,c.width,c.height)});
function val(id){return document.getElementById(id)?.value||''}function checked(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||''}
function collect(){const controls={};sections.forEach(([title,items],si)=>items.forEach((it,i)=>controls[it]=checked(`c_${si}_${i}`)));return {maintenance:checked('maintenance'),marque:val('marque'),annee:val('annee'),serie:val('serie'),barrieres:checked('barrieres'),serieBar:val('serieBar'),potence:checked('potence'),seriePot:val('seriePot'),env:checked('env'),client:val('client'),localisation:val('localisation'),adresse:val('adresse'),ville:val('ville'),reference:val('reference'),observations:val('observations'),pieces:val('pieces'),securite:checked('securite'),date:val('date'),technicien:val('technicien'),controls, sigTech:sigTech.toDataURL('image/png'),sigClient:sigClient.toDataURL('image/png')}}
function safe(s){return String(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
async function makePDF(){const d=collect(),{jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});const W=210,M=10;pdf.setFont('helvetica');pdf.setFontSize(8);pdf.text('ENR08-V05',W-M,8,{align:'right'});pdf.addImage(document.querySelector('.top img').src,'JPEG',M,5,48,17);pdf.setFontSize(14);pdf.setFont('helvetica','bold');pdf.text('FICHE DE MAINTENANCE LIT MÉDICALISÉ',W/2,29,{align:'center'});pdf.setFontSize(8);pdf.setFont('helvetica','normal');pdf.text(`Maintenance : ${d.maintenance||'—'}`,W/2,35,{align:'center'});
let y=41;const line=(text,x,w)=>{pdf.text(text,x,y);pdf.line(x,y+1,x+w,y+1)};pdf.setDrawColor(100);pdf.rect(M,y,W-2*M,40);pdf.setFont('helvetica','bold');pdf.text('IDENTIFICATION',M+3,y+5);pdf.text('LOCALISATION',110,y+5);pdf.setFont('helvetica','normal');let left=[`Marque / modèle : ${d.marque}`,`Année de fabrication : ${d.annee}`,`N° série / parc : ${d.serie}`,`Barrières : ${d.barrieres}   N° : ${d.serieBar}`,`Potence : ${d.potence}   N° : ${d.seriePot}`,`Environnement : ${d.env}`],right=[`Établissement / client : ${d.client}`,`Service / chambre : ${d.localisation}`,`Adresse : ${d.adresse}`,`Ville : ${d.ville}`,`Réf. intervention : ${d.reference}`];left.forEach((s,i)=>pdf.text(s,M+3,y+11+i*5.5));right.forEach((s,i)=>pdf.text(s,110,y+11+i*5.5));y+=45;
for(const [title,items] of sections){pdf.setFont('helvetica','bold');pdf.setFillColor(232,238,241);pdf.rect(M,y,W-2*M,6,'F');pdf.text(title,M+2,y+4.2);y+=7;pdf.setFont('helvetica','normal');for(const it of items){if(y>270){pdf.addPage();y=12}pdf.rect(M,y,W-2*M,7);pdf.text(it,M+2,y+4.5,{maxWidth:128});const key=it;pdf.text(d.controls[key]||'—',172,y+4.5,{align:'center'});y+=7}y+=2}
if(y>240){pdf.addPage();y=12}pdf.setFont('helvetica','bold');pdf.text('OBSERVATIONS :',M,y+4);pdf.text('PIÈCES CHANGÉES :',110,y+4);pdf.rect(M,y+6,90,35);pdf.rect(110,y+6,90,35);pdf.setFont('helvetica','normal');pdf.text(pdf.splitTextToSize(d.observations||'',86),M+2,y+11);pdf.text(pdf.splitTextToSize(d.pieces||'',86),112,y+11);y+=45;pdf.text(`Rappel des consignes de sécurité : ${d.securite||'—'}`,M,y);pdf.text('* suivant norme NF EN 60601-2-52',M,y+5);pdf.text(`Fait le : ${d.date||'—'}    Technicien : ${d.technicien||'—'}`,M,y+12);pdf.setFont('helvetica','bold');pdf.text('Signature du technicien',M,y+19);pdf.text('Signature du client',110,y+19);pdf.rect(M,y+21,90,30);pdf.rect(110,y+21,90,30);if(d.sigTech)pdf.addImage(d.sigTech,'PNG',M+2,y+23,86,26);if(d.sigClient)pdf.addImage(d.sigClient,'PNG',112,y+23,86,26);return {pdf,data:d}};

document.getElementById('pdf').onclick=async()=>{const {pdf,data}=await makePDF();pdf.save(`ENR08-V05_${data.serie||'maintenance'}_${data.date||''}.pdf`)};
document.getElementById('send').onclick=async()=>{const status=document.getElementById('status');try{status.textContent='Préparation du PDF…';const {pdf,data}=await makePDF();const filename=`ENR08-V05_${data.serie||'maintenance'}_${data.date||''}.pdf`;if(APPS_SCRIPT_URL==='A_REMPLACER'){status.textContent='URL Google Apps Script non configurée : le PDF va être téléchargé.';pdf.save(filename);return}status.textContent='Envoi du PDF…';const b64=pdf.output('datauristring').split(',')[1];const params=new URLSearchParams({token:APP_TOKEN,pdf_base64:b64,filename,client:data.client,technicien:data.technicien,date:data.date,reference:data.reference,serie:data.serie});await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:params.toString()});status.textContent=`Demande d’envoi transmise à ${EMAIL_TO}. Vérifiez la boîte de réception.`;}catch(e){console.error(e);status.textContent='Erreur lors de la transmission. Le PDF va être téléchargé.';try{const {pdf,data}=await makePDF();pdf.save(`ENR08-V05_${data.serie||'maintenance'}_${data.date||''}.pdf`)}catch(_){} }};
